### ISSUE TITLE
client.RequestForm clobbers intentional uses of '\.'

### ISSUE THREAD

**Issue by alienth** [sethvargo/go-fastly#11]
This function attempts to workaround a quirk of the form library where cases of `.` characters are replaced with `%5C.`. 

https://github.com/sethvargo/go-fastly/blob/master/client.go#L164

Problem is when it does this, it replaces intentional cases of `\.`. For example, a VCL I'm uploading has a `\.` within a regex, which this code clobbers and replaces with a bare `.`.

**Comment by sethvargo** [comment]
Hi @alienth 

Can you please submit a test that shows the failling behavior and I'll fix it up right away?

**Comment by alienth** [comment]
@sethvargo , here ya go. Thanks for looking into this!

```
package main

import (
        "fmt"
        "github.com/sethvargo/go-fastly"
)

func main() {
        client, _ := fastly.NewClient("foo")
        myvcl := "if (req.http.host ~ \"([[:alnum:]]+)\\.([[:alnum:]]+)$\") {"
        fmt.Println(myvcl)
        vcl, _ := client.UpdateVCL(&fastly.UpdateVCLInput{Name: "myvcl", Service: "abcdef0123456789", Version: "1", Content: myvcl})
        fmt.Println(vcl.Content)
}
```

The output of this will be as follows:

```
if (req.http.host ~ "([[:alnum:]]+)\.([[:alnum:]]+)$") {
if (req.http.host ~ "([[:alnum:]]+).([[:alnum:]]+)$") {
```

You can also verify on Fastly that the resulting VCL is missing the all important `\`.

I've verified that ripping the `strings.Replace` out of `RequestForm()` fixes this, and it also doesn't appear to cause any unwanted escapes. You can see an example of the form lib DTRT in my comment about.

**Comment by sethvargo** [comment]
Hi @alienth 

Sadly this is not fixed upstream. Take a look at `settings.go`. The form keys use a "." such as "general.default_ttl". When removing that value, the submitted form is:

```
Service=xxx&Version=1&general%5C.default_ttl=1234
```

Fastly expects that to be a dot, and the settings fail 😦

**Comment by alienth** [comment]
Ahh, so perhaps this only happens for form keys? As you saw in my test, values seemed to be AOK.

**Comment by sethvargo** [comment]
Maybe, but I'm still not really following the issue. Also, there's no way to just reverse the behavior on just the keys.

I don't think that function is stripping out the slash... it shouldn't touch slashes at all.

**Comment by alienth** [comment]
What is happening is that form is appropriately escaping my backslash, which turns it into `%5E`. From there, `client.RequestCode()` rips out the `%5E`, which I actually want to have, along with any unwanted `%5E`s.

With some testing I've verified that the form lib is only doing the unwanted escaping that you're trying to compensate for on form keys. The values are untouched.

**Comment by alienth** [comment]
A test case showing that it is only escaping the form key specified in the tag:

```
package main

import (
        "fmt"
        "github.com/ajg/form"
)

func main() {
        type test struct {
                Test string `form:"general.default_ttl,omitempty"`
        }
        testing := test{Test: "not.escaping"}
        values, _ := form.EncodeToValues(testing)
        fmt.Println(values.Encode())
}
```

Output:

```
general%5C.default_ttl=not.escaping
```

**Comment by alienth** [comment]
@sethvargo Looks like this is intended functionality by form. I don't think they'll be changing it: https://github.com/ajg/form#keys

> However, periods have special meaning to form, and thus, under the hood (i.e. in encoded form) they are transparently escaped using a preceding backslash (\).

**Comment by alienth** [comment]
@sethvargo Found a more robust workaround which fixes my case. PR will be incoming shortly.
