### ISSUE TITLE
DefaultTTL cannot be set to 0

### ISSUE THREAD

**Issue by keshavdv** [sethvargo/go-fastly#20]
In cases where I'd like to disable Fastly caching by default, I would set the default TTL to 0. However, the use of omitempty in the UpdateSettingsInput struct means that the TTL field is omitted entirely if the value is set to 0. A possible solution is to make the field required by removing the omitempty tag or turning DefaultTTL into a pointer. I'm glad to make a PR for either approach but wanted to hear your thoughts.

**Comment by keshavdv** [comment]
It seems that even with some modification, the underlying library results in incorrect behavior (https://github.com/ajg/form/issues/11).

**Comment by aerostitch** [comment]
Proposed a fix in #41
