### ISSUE TITLE
Create a release tag for pinning purposes

### ISSUE THREAD

**Issue by udryan10** [sethvargo/go-fastly#29]
We use glide for dependency management. It would be ideal to have a release tag that we can pin against.

**Comment by sethvargo** [comment]
Hi @udryan10 

Thank you for opening an issue. In general, I do not think it makes sense to apply arbitrary tags to a client library. If you want to pin, I would recommend pinning to a SHA (which glide supports), or forking, applying your own tags, and then re-tagging as necessary from your own repo. Thanks!

**Comment by rabdill** [comment]
Hi Seth -- obviously it's your right to manage your repo however you see fit, I'm just curious about the decision here; I think I'm missing something. I agree "arbritrary" tags don't make sense, but in a lib without a changelog or versioning scheme, how should users figure out when breaking changes come in? Sure, testing can catch some of it in projects that are pulling in go-fastly, but is that a valid work-around for avoiding semantic versioning?
