### ISSUE TITLE
message_type for syslog logging

### ISSUE THREAD

**Issue by karnauskas** [sethvargo/go-fastly#49]
syslog logging is missing message_type parameter. It's similar to s3 or gce logging.

**Comment by sethvargo** [comment]
Hi @karnauskas 

Could you please point to the Fastly API documentation where this option is listed?

**Comment by karnauskas** [comment]
Hi @sethvargo 

It's here https://docs.fastly.com/api/logging#logging_syslog, look for message_type.

Thanks
