### ISSUE TITLE
jsonapi does not work with responses that have int ID's

### ISSUE THREAD

**Issue by bridgetlane** [sethvargo/go-fastly#56]
I'm trying to add [GET /wafs/rules](https://docs.fastly.com/api/waf#waf_rule_a088fb59b30ff988d86088dca4f6ecf2) to the waf functionality. The response returns and ID as an integer, and jsonapi does not seem to want to unmarshal it and consistently returns:
`json: cannot unmarshal number into Go struct field Node.id of type string`
I tried editing the payload from Fastly so that the top level ID was a string rather than an int, and jsonapi was then able to unmarshal it fine. I'm not sure the desired way to handle this behavior?
I can provide a more in-depth example if needed.

**Comment by udryan10** [comment]
It appears that the fastly return data:
```
{
   "data": [
      {
         "type": "rule",
         "id": 949120,
         "attributes": {
            "version": null,
            "revision": null,
            "rule_id": 949120,
            "severity": 2,
            "accuracy": null,
            "maturity": null,
            "message": "Cross-site Scripting (XSS) Anomaly Threshold Exceeded (XSS Score: %{TX.XSS_SCORE})"
            "source": null,
            "vcl": null,
         }
      }
   ],
   "links": {
      "last": "https://api.fastly.com/wafs/rules?page[number]=204&page[size]=1",
      "first": "https://api.fastly.com/wafs/rules?page[number]=1&page[size]=1",
      "next": "https://api.fastly.com/wafs/rules?page[number]=2&page[size]=1"
   }
}
```

which has its ID's as ints, is not actually adhering to the jsonapi spec which requires ids to be strings:

http://jsonapi.org/format/#document-resource-object-identification

**Comment by bridgetlane** [comment]
Fastly has pushed an update to fix this, marking resolved.
