### ISSUE TITLE
Add fake package

### ISSUE THREAD

**Issue by bridgetlane** [sethvargo/go-fastly#67]
It would be nice to add the ability to make a fake client for tests and mocking, so that we can use go-fastly in code that has mocked testing.

**Comment by sethvargo** [comment]
Hey @bridgetlane 

Can you use [NewClientForEndpoint](https://github.com/sethvargo/go-fastly/blob/4c86d131640b9e67f29f6bf4716af1135e68ecff/fastly/client.go#L84-L91) and point to a stubbed http server?

**Comment by bridgetlane** [comment]
@sethvargo thanks for pointing this out, I might be able to make that work. Will give it a shot!
